package com.jb.ui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.jb.controller.UIController;
import com.jb.service.InventoryDBService;

/**
 *
 * @author ashwa
 */
public class SalesAssociateForm extends javax.swing.JFrame {

    /**
     * Creates new form SalesAssociate
     */
    public SalesAssociateForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        saleSuccess = new javax.swing.JDialog();
        sellSuccessLabel = new javax.swing.JLabel();
        sellSuccessOkButton = new javax.swing.JButton();
        skuLabelSell = new javax.swing.JLabel();
        quantityLabelSell = new javax.swing.JLabel();
        quantityFieldSell = new javax.swing.JTextField();
        skuFieldSell = new javax.swing.JTextField();
        sellButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salesAssocBackButton = new javax.swing.JButton();

        saleSuccess.setSize(new java.awt.Dimension(300, 200));

        sellSuccessLabel.setText("Sold item(s) successfully.");

        sellSuccessOkButton.setText("Ok");
        sellSuccessOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellSuccessOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saleSuccessLayout = new javax.swing.GroupLayout(saleSuccess.getContentPane());
        saleSuccess.getContentPane().setLayout(saleSuccessLayout);
        saleSuccessLayout.setHorizontalGroup(
                saleSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saleSuccessLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(saleSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sellSuccessOkButton)
                                        .addComponent(sellSuccessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGap(137, 137, 137))
        );
        saleSuccessLayout.setVerticalGroup(
                saleSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(saleSuccessLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(sellSuccessLabel)
                                .addGap(18, 18, 18)
                                .addComponent(sellSuccessOkButton)
                                .addContainerGap(59, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        skuLabelSell.setText("Item SKU:");

        quantityLabelSell.setText("Quantity:");

        quantityFieldSell.setToolTipText("");

        skuFieldSell.setToolTipText("");

        sellButton.setText("Sell");
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Sales Associate");

        salesAssocBackButton.setText("Back");
        salesAssocBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesAssocBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(sellButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(salesAssocBackButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(skuLabelSell, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(quantityLabelSell))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(skuFieldSell, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(quantityFieldSell, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)))
                                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(skuLabelSell)
                                        .addComponent(skuFieldSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(quantityLabelSell)
                                        .addComponent(quantityFieldSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(salesAssocBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {
            inventoryDBService.updateShelfQuantity(Integer.parseInt(skuFieldSell.getText()), Integer.parseInt(quantityFieldSell.getText()), 1);
            saleSuccess.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void salesAssocBackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        UIController.uiController.showRoleSelector();
    }

    private void sellSuccessOkButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        saleSuccess.setVisible(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesAssociateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesAssociateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesAssociateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesAssociateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesAssociateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField quantityFieldSell;
    private javax.swing.JLabel quantityLabelSell;
    private javax.swing.JDialog saleSuccess;
    private javax.swing.JButton salesAssocBackButton;
    private javax.swing.JButton sellButton;
    private javax.swing.JLabel sellSuccessLabel;
    private javax.swing.JButton sellSuccessOkButton;
    private javax.swing.JTextField skuFieldSell;
    private javax.swing.JLabel skuLabelSell;
    public static InventoryDBService inventoryDBService = new InventoryDBService();
    // End of variables declaration
}
