package com.jb.ui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.jb.controller.UIController;

/**
 *
 * @author ashwa
 */
public class StockAssociateForm extends javax.swing.JFrame {

    /**
     * Creates new form StockAssociateForm
     */
    public StockAssociateForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        stockSuccess = new javax.swing.JDialog();
        checkInSuccessLabel = new javax.swing.JLabel();
        checkInSuccessOkButton = new javax.swing.JButton();
        skuLabelStock = new javax.swing.JLabel();
        quantityLabelStock = new javax.swing.JLabel();
        quantityFieldStock = new javax.swing.JTextField();
        skuFieldStock = new javax.swing.JTextField();
        stockButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        stockAssocBackButton = new javax.swing.JButton();

        stockSuccess.setSize(new java.awt.Dimension(300, 200));

        checkInSuccessLabel.setText("Stocked item(s) successfully.");

        checkInSuccessOkButton.setText("Ok");
        checkInSuccessOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInSuccessOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stockSuccessLayout = new javax.swing.GroupLayout(stockSuccess.getContentPane());
        stockSuccess.getContentPane().setLayout(stockSuccessLayout);
        stockSuccessLayout.setHorizontalGroup(
                stockSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stockSuccessLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(stockSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkInSuccessOkButton)
                                        .addComponent(checkInSuccessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGap(137, 137, 137))
        );
        stockSuccessLayout.setVerticalGroup(
                stockSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(stockSuccessLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(checkInSuccessLabel)
                                .addGap(18, 18, 18)
                                .addComponent(checkInSuccessOkButton)
                                .addContainerGap(59, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        skuLabelStock.setText("Item SKU:");

        quantityLabelStock.setText("Quantity:");

        quantityFieldStock.setToolTipText("");

        skuFieldStock.setToolTipText("");

        stockButton.setText("Stock");
        stockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Stock Associate");

        stockAssocBackButton.setText("Back");
        stockAssocBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockAssocBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(stockButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(stockAssocBackButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(skuLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(quantityLabelStock))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(skuFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(quantityFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)))
                                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(skuLabelStock)
                                        .addComponent(skuFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(quantityLabelStock)
                                        .addComponent(quantityFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(stockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stockAssocBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void stockButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        stockSuccess.setVisible(true);
    }

    private void checkInSuccessOkButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        stockSuccess.setVisible(false);
    }

    private void stockAssocBackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        UIController.uiController.showRoleSelector();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockAssociateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockAssociateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockAssociateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockAssociateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockAssociateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel checkInSuccessLabel;
    private javax.swing.JButton checkInSuccessOkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField quantityFieldStock;
    private javax.swing.JLabel quantityLabelStock;
    private javax.swing.JTextField skuFieldStock;
    private javax.swing.JLabel skuLabelStock;
    private javax.swing.JButton stockAssocBackButton;
    private javax.swing.JButton stockButton;
    private javax.swing.JDialog stockSuccess;
    // End of variables declaration
}
