package com.jb.ui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.jb.controller.UIController;

/**
 *
 * @author ashwa
 */
public class WarehouseManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form WarehouseManagerUI
     */
    public WarehouseManagerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        checkInSuccess = new javax.swing.JDialog();
        checkInSuccessLabel = new javax.swing.JLabel();
        checkInSuccessOkButton = new javax.swing.JButton();
        checkOutSuccess = new javax.swing.JDialog();
        checkOutSuccessLabel = new javax.swing.JLabel();
        checkOutSuccessOkButton = new javax.swing.JButton();
        warehouseTabbedPane = new javax.swing.JTabbedPane();
        checkOutPanel = new javax.swing.JPanel();
        checkOutButton = new javax.swing.JButton();
        quantityField = new javax.swing.JTextField();
        skuLabelCheckOut = new javax.swing.JLabel();
        employeeIDLabelCheckOut = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        employeeIDFieldCbeckOut = new javax.swing.JTextField();
        skuFieldCheckOut = new javax.swing.JTextField();
        warehouseMgrBackButton = new javax.swing.JButton();
        checkInPanel = new javax.swing.JPanel();
        skuLabelCheckIn = new javax.swing.JLabel();
        quantityLabelCheckIn = new javax.swing.JLabel();
        quantityFieldCheckIn = new javax.swing.JTextField();
        skuFieldCheckIn = new javax.swing.JTextField();
        checkInButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        checkInSuccessLabel.setText("Checked item(s) in successfully.");

        checkInSuccessOkButton.setText("Ok");
        checkInSuccessOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInSuccessOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkInSuccessLayout = new javax.swing.GroupLayout(checkInSuccess.getContentPane());
        checkInSuccess.getContentPane().setLayout(checkInSuccessLayout);
        checkInSuccessLayout.setHorizontalGroup(
                checkInSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkInSuccessLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(checkInSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkInSuccessOkButton)
                                        .addComponent(checkInSuccessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGap(137, 137, 137))
        );
        checkInSuccessLayout.setVerticalGroup(
                checkInSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkInSuccessLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(checkInSuccessLabel)
                                .addGap(18, 18, 18)
                                .addComponent(checkInSuccessOkButton)
                                .addContainerGap(59, Short.MAX_VALUE))
        );

        checkOutSuccessLabel.setText("Checked item(s) out successfully.");

        checkOutSuccessOkButton.setText("Ok");
        checkOutSuccessOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutSuccessOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkOutSuccessLayout = new javax.swing.GroupLayout(checkOutSuccess.getContentPane());
        checkOutSuccess.getContentPane().setLayout(checkOutSuccessLayout);
        checkOutSuccessLayout.setHorizontalGroup(
                checkOutSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutSuccessLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(checkOutSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkOutSuccessOkButton)
                                        .addComponent(checkOutSuccessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGap(137, 137, 137))
        );
        checkOutSuccessLayout.setVerticalGroup(
                checkOutSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkOutSuccessLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(checkOutSuccessLabel)
                                .addGap(18, 18, 18)
                                .addComponent(checkOutSuccessOkButton)
                                .addContainerGap(59, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkOutButton.setText("Check out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        quantityField.setToolTipText("");

        skuLabelCheckOut.setText("Item SKU:");

        employeeIDLabelCheckOut.setText("Employee ID:");

        quantityLabel.setText("Quantity:");

        employeeIDFieldCbeckOut.setToolTipText("");

        skuFieldCheckOut.setToolTipText("");

        warehouseMgrBackButton.setText("Back");
        warehouseMgrBackButton.setAutoscrolls(true);
        warehouseMgrBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseMgrBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkOutPanelLayout = new javax.swing.GroupLayout(checkOutPanel);
        checkOutPanel.setLayout(checkOutPanelLayout);
        checkOutPanelLayout.setHorizontalGroup(
                checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkOutPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(checkOutPanelLayout.createSequentialGroup()
                                                .addComponent(checkOutButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(warehouseMgrBackButton))
                                        .addGroup(checkOutPanelLayout.createSequentialGroup()
                                                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(skuLabelCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(employeeIDLabelCheckOut))
                                                        .addComponent(quantityLabel))
                                                .addGap(20, 20, 20)
                                                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(skuFieldCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(employeeIDFieldCbeckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(179, Short.MAX_VALUE))
        );
        checkOutPanelLayout.setVerticalGroup(
                checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkOutPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(skuLabelCheckOut)
                                        .addComponent(skuFieldCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(employeeIDLabelCheckOut)
                                        .addComponent(employeeIDFieldCbeckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(quantityLabel)
                                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(checkOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(warehouseMgrBackButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        warehouseTabbedPane.addTab("Check Out Items", checkOutPanel);

        skuLabelCheckIn.setText("Item SKU:");

        quantityLabelCheckIn.setText("Quantity:");

        quantityFieldCheckIn.setToolTipText("");

        skuFieldCheckIn.setToolTipText("");

        checkInButton.setText("Check in");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkInPanelLayout = new javax.swing.GroupLayout(checkInPanel);
        checkInPanel.setLayout(checkInPanelLayout);
        checkInPanelLayout.setHorizontalGroup(
                checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkInPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkInButton)
                                        .addGroup(checkInPanelLayout.createSequentialGroup()
                                                .addGroup(checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(skuLabelCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(quantityLabelCheckIn))
                                                .addGap(20, 20, 20)
                                                .addGroup(checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(skuFieldCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(quantityFieldCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(186, Short.MAX_VALUE))
        );
        checkInPanelLayout.setVerticalGroup(
                checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkInPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(skuLabelCheckIn)
                                        .addComponent(skuFieldCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(quantityLabelCheckIn)
                                        .addComponent(quantityFieldCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(checkInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        warehouseTabbedPane.addTab("Check In Items", checkInPanel);

        jLabel1.setText("Warehouse Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(warehouseTabbedPane)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(warehouseTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        checkOutSuccess.setSize(300, 200);
        checkOutSuccess.setVisible(true);

    }

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        checkInSuccess.setSize(300, 200);
        checkInSuccess.setVisible(true);
    }

    private void checkInSuccessOkButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        checkInSuccess.setVisible(false);
    }

    private void checkOutSuccessOkButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        checkOutSuccess.setVisible(false);
    }

    private void warehouseMgrBackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        UIController.uiController.showRoleSelector();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarehouseManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarehouseManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarehouseManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehouseManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarehouseManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton checkInButton;
    private javax.swing.JPanel checkInPanel;
    private javax.swing.JDialog checkInSuccess;
    private javax.swing.JLabel checkInSuccessLabel;
    private javax.swing.JButton checkInSuccessOkButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JPanel checkOutPanel;
    private javax.swing.JDialog checkOutSuccess;
    private javax.swing.JLabel checkOutSuccessLabel;
    private javax.swing.JButton checkOutSuccessOkButton;
    private javax.swing.JTextField employeeIDFieldCbeckOut;
    private javax.swing.JLabel employeeIDLabelCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField quantityFieldCheckIn;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityLabelCheckIn;
    private javax.swing.JTextField skuFieldCheckIn;
    private javax.swing.JTextField skuFieldCheckOut;
    private javax.swing.JLabel skuLabelCheckIn;
    private javax.swing.JLabel skuLabelCheckOut;
    private javax.swing.JButton warehouseMgrBackButton;
    private javax.swing.JTabbedPane warehouseTabbedPane;
    // End of variables declaration
}
